version : '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: users-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userDB
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'